<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    public function run()
    {
        $services = [
            // BEDCOVER CATEGORY
            [
                'name' => 'Bedcover Small',
                'description' => 'Bedcover ukuran kecil',
                'price' => 10000,
                'member_price' => 9000,
                'category' => 'Bedcover',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Bedcover Medium',
                'description' => 'Bedcover ukuran sedang',
                'price' => 12000,
                'member_price' => 11000,
                'category' => 'Bedcover',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Bedcover King',
                'description' => 'Bedcover ukuran king',
                'price' => 15000,
                'member_price' => 14000,
                'category' => 'Bedcover',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Bedcover Super King',
                'description' => 'Bedcover ukuran super king',
                'price' => 18000,
                'member_price' => 17000,
                'category' => 'Bedcover',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],

            // SELIMUT CATEGORY
            [
                'name' => 'Selimut Tipis',
                'description' => 'Selimut tipis',
                'price' => 8000,
                'member_price' => 7000,
                'category' => 'Selimut',
                'duration' => '24 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Selimut Sedang',
                'description' => 'Selimut sedang',
                'price' => 10000,
                'member_price' => 9000,
                'category' => 'Selimut',
                'duration' => '24 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Selimut Tebal',
                'description' => 'Selimut tebal',
                'price' => 12000,
                'member_price' => 11000,
                'category' => 'Selimut',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Selimut King',
                'description' => 'Selimut ukuran king',
                'price' => 15000,
                'member_price' => 14000,
                'category' => 'Selimut',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],

            // CUCI KERING GOSOK (CKG) - EXPRESS
            [
                'name' => 'CKG Express 4 Jam',
                'description' => 'Cuci Kering Gosok Express 4 jam',
                'price' => 12000,
                'member_price' => 11000,
                'category' => 'Express',
                'duration' => '4 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKG Express 6 Jam',
                'description' => 'Cuci Kering Gosok Express 6 jam',
                'price' => 18000,
                'member_price' => 17000,
                'category' => 'Express',
                'duration' => '6 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKG Express 12 Jam',
                'description' => 'Cuci Kering Gosok Express 12 jam',
                'price' => 8000,
                'member_price' => 7500,
                'category' => 'Express',
                'duration' => '12 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKG Express 1 Hari',
                'description' => 'Cuci Kering Gosok Express 1 hari',
                'price' => 7000,
                'member_price' => 6500,
                'category' => 'Express',
                'duration' => '24 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],

            // CKG REGULER
            [
                'name' => 'CKG Reguler 2 Hari',
                'description' => 'Cuci Kering Gosok Reguler 2 hari',
                'price' => 6000,
                'member_price' => 5500,
                'category' => 'Reguler',
                'duration' => '48 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKG Reguler 3 Hari',
                'description' => 'Cuci Kering Gosok Reguler 3 hari',
                'price' => 5000,
                'member_price' => 4500,
                'category' => 'Reguler',
                'duration' => '72 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],

            // CUCI KERING LIPAT (CKL) - EXPRESS
            [
                'name' => 'CKL Express 4 Jam',
                'description' => 'Cuci Kering Lipat Express 4 jam',
                'price' => 10000,
                'member_price' => 9500,
                'category' => 'Express',
                'duration' => '4 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKL Express 6 Jam',
                'description' => 'Cuci Kering Lipat Express 6 jam',
                'price' => 9000,
                'member_price' => 8500,
                'category' => 'Express',
                'duration' => '6 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKL Express 12 Jam',
                'description' => 'Cuci Kering Lipat Express 12 jam',
                'price' => 7000,
                'member_price' => 6500,
                'category' => 'Express',
                'duration' => '12 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],

            // CKL REGULER
            [
                'name' => 'CKL Reguler 1 Hari',
                'description' => 'Cuci Kering Lipat Reguler 1 hari',
                'price' => 6000,
                'member_price' => 5500,
                'category' => 'Reguler',
                'duration' => '24 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKL Reguler 2 Hari',
                'description' => 'Cuci Kering Lipat Reguler 2 hari',
                'price' => 5500,
                'member_price' => 5000,
                'category' => 'Reguler',
                'duration' => '48 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],
            [
                'name' => 'CKL Reguler 3 Hari',
                'description' => 'Cuci Kering Lipat Reguler 3 hari',
                'price' => 5000,
                'member_price' => 4500,
                'category' => 'Reguler',
                'duration' => '72 jam',
                'is_weight_based' => true,
                'is_active' => true,
            ],

            // SPECIAL ITEMS (dari gambar 2)
            [
                'name' => 'Timbang Cucian',
                'description' => 'Layanan timbang cucian',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Khusus',
                'duration' => '0 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Hitung Pakaian',
                'description' => 'Layanan hitung pakaian',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Khusus',
                'duration' => '0 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Tempel Nota',
                'description' => 'Tempel nota pada pakaian',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Khusus',
                'duration' => '0 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Sortir Pakaian Sesuai Warna',
                'description' => 'Sortir pakaian berdasarkan warna',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Khusus',
                'duration' => '0 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Proses Produksi (Kiloan)',
                'description' => 'Proses produksi untuk layanan kiloan',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Proses',
                'duration' => '0 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],

            // TREATMENT ITEMS
            [
                'name' => 'Treatment Item - Jas',
                'description' => 'Treatment khusus untuk jas',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Tas',
                'description' => 'Treatment khusus untuk tas',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Selimut',
                'description' => 'Treatment khusus untuk selimut',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Bed Cover',
                'description' => 'Treatment khusus untuk bed cover',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Sepatu',
                'description' => 'Treatment khusus untuk sepatu',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Topi',
                'description' => 'Treatment khusus untuk topi',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '24 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Sajadah',
                'description' => 'Treatment khusus untuk sajadah',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '24 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Karpet',
                'description' => 'Treatment khusus untuk karpet',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '72 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Gordeng',
                'description' => 'Treatment khusus untuk gordeng',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '72 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Treatment Item - Vitrase',
                'description' => 'Treatment khusus untuk vitrase',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Treatment',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],

            // PROSES PRODUKSI SATUAN / DRY CLEAN
            [
                'name' => 'Proses Produksi Satuan - Sepatu',
                'description' => 'Dry clean satuan untuk sepatu',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Satuan',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Proses Produksi Satuan - Tas',
                'description' => 'Dry clean satuan untuk tas',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Satuan',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Proses Produksi Satuan - Karpet',
                'description' => 'Dry clean satuan untuk karpet',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Satuan',
                'duration' => '72 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Proses Produksi Satuan - Gordeng',
                'description' => 'Dry clean satuan untuk gordeng',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Satuan',
                'duration' => '72 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Proses Produksi Satuan - Vitrase',
                'description' => 'Dry clean satuan untuk vitrase',
                'price' => 0,
                'member_price' => 0,
                'category' => 'Satuan',
                'duration' => '48 jam',
                'is_weight_based' => false,
                'is_active' => true,
            ],
        ];

        foreach ($services as $service) {
            DB::table('services')->insert(array_merge($service, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
